### ISSUE TITLE
Problems about adding 3D models into InfiniTAM

### ISSUE THREAD

**Issue by MarkZurkberg** [Masterxilo/InfiniTAM#30]
I have used glm(a opengl math library) to load a 3D object successfully, but I don't know how to integrate this with InfiniTAM so now it is just limited in its own window. I want to find the entry point for the reconstruction scene so that I can add some 3D models like furnitures into InfiniTAM. Could you please give me some advice? Thanks! @Masterxilo

**Comment by Masterxilo** [comment]
Hi there. 

You have to set up the depth buffer of opengl with the depth buffer generated by the raytracing routine of infinitam in order to mix opengl-rendered 3d models with the infinitam output.
(I have done this to render some simple lines with opengl on top of the output; maybe I have not pushed that code yet).

Alternatively you could convert your models to volumetric data and integrate that, or render the volumetric scene with opengl (a geometry shader might do the trick).

Anyways, you should ask the original infinitam developers for help with InfiniTAM. I'm the only person working on this derivative project really. The only reason it's public is that I don't care about making it private.

Have a nice day.

**Comment by MarkZurkberg** [comment]
Thanks!
